// Generated by Gemini

package main

import (
	E "github.com/sagernet/sing/common/exceptions"

	"golang.org/x/sys/windows"
)

func checkPermission() error {
	var sid *windows.SID

	// Although this looks scary, it is okay to impersonate ourselves
	// The token generated is restricted to the current user
	err := windows.AllocateAndInitializeSid(
		&windows.SECURITY_NT_AUTHORITY,
		2,
		windows.SECURITY_BUILTIN_DOMAIN_RID,
		windows.DOMAIN_ALIAS_RID_ADMINS,
		0, 0, 0, 0, 0, 0,
		&sid,
	)
	if err != nil {
		return E.Cause(err, "AllocateAndInitializeSid")
	}
	defer windows.FreeSid(sid)

	// Check if the current user is a member of the local Administrators group
	token := windows.Token(0)
	member, err := token.IsMember(sid)
	if err != nil {
		return E.Cause(err, "token")
	}
	if !member {
		return E.New("not administrator")
	}

	return nil
}
